{% set name = "spin" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spin-{{ version }}.tar.gz
  sha256: 3f20f1d19e0153832804891eec3f3691effd2d1def95bdd6c0c4b97cb41a0a1f

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<37]
  entry_points:
    - spin = spin.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - click
    - toml
    - colorama  # [win]

test:
  files:
    - example_pkg/**
  imports:
    - spin
  commands:
    - pip check
    - cd example_pkg && python -m spin build
  requires:
    - pip
    - meson

about:
  home: https://github.com/scientific-python/spin
  dev_url: https://github.com/scientific-python/spin
  doc_url: https://github.com/scientific-python/spin/blob/main/README.md
  summary: Developer tool for scientific Python libraries
  description: |
    Formarly known as `devpy`, `spin` aims to provide a simple interface 
    for common development tasks. It comes with a few common build commands 
    out the box, but can easily be customized per project.
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - hmaarrfk
