{% set name = "spin" %}
{% set version = "0.18" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spin-{{ version }}.tar.gz
  sha256: 1c8e8d1d67f20f9bfce0bbe43cff4131d728de4d1905d90ee3d8b29b17320006

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<310]
  entry_points:
    - spin = spin.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - click >=8,!=8.3.0,<8.4
    - tomli  # [py<311]
    - colorama  # [win]
    - importlib-metadata >=7

test:
  files:
    - example_pkg/**
  imports:
    - spin
  commands:
    - pip check
    - cd example_pkg && python -m spin build
  requires:
    - pip
    - meson
    - ninja-base
    - {{ compiler('cxx') }}  # [linux]
    - {{ compiler('c') }}  # [linux]

about:
  home: https://github.com/scientific-python/spin
  dev_url: https://github.com/scientific-python/spin
  doc_url: https://github.com/scientific-python/spin/blob/main/README.md
  summary: Developer tool for scientific Python libraries
  description: |
    Formarly known as `devpy`, `spin` aims to provide a simple interface
    for common development tasks. It comes with a few common build commands
    out the box, but can easily be customized per project.
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - hmaarrfk
