{% set name = "spin" %}
{% set version = "0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/spin-{{ version }}.tar.gz
  sha256: 1a5f6ce53699ef58bf893970ecb9d7f8814a8ca08da5d26e1391fe2a9fa04bcc

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<39]
  entry_points:
    - spin = spin.__main__:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - click
    - tomli  # [py<311]
    - importlib_metadata >=7
    - colorama  # [win]

test:
  files:
    - example_pkg/**
  imports:
    - spin
  commands:
    - pip check
    - cd example_pkg && python -m spin build
  requires:
    - pip
    - meson
    - {{ compiler('cxx') }}  # [linux]
    - {{ compiler('c') }}  # [linux]

about:
  home: https://github.com/scientific-python/spin
  dev_url: https://github.com/scientific-python/spin
  doc_url: https://github.com/scientific-python/spin/blob/main/README.md
  summary: Developer tool for scientific Python libraries
  description: |
    Formarly known as `devpy`, `spin` aims to provide a simple interface 
    for common development tasks. It comes with a few common build commands 
    out the box, but can easily be customized per project.
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - hmaarrfk
